# Site settings
author: Yevgeniy Brikman
title: "Hello, Startup: A Programmer's Guide to Building Products, Technologies, and Teams -- an O'Reilly book by Yevgeniy Brikman."
twitter_title: "Hello, Startup: A Programmer's Guide to Building Products, Technologies, and Teams -- an O'Reilly book by @brikis98."
short_title: "Hello, Startup"
medium_title: "Hello, Startup: A Programmer's Guide to Building Products, Technologies, and Teams"
email: feedback@hello-startup.net
image: "http://www.hello-startup.net/images/hello-startup-large.jpg"
baseurl: ""
url: "http://www.hello-startup.net"
twitter_username: brikis98
twitter_url: "https://twitter.com/brikis98"
homepage: "http://www.ybrikman.com"
github: "https://github.com/brikis98"
blog: "http://brikis98.blogspot.com/"
talks: "http://ybrikman.com/talks"
photos: "http://ybrikman.com/photos"
linkedin: "https://www.linkedin.com/in/jbrikman"
buy_oreilly_link: "http://www.jdoqocy.com/click-7745743-11290546?url=http%3A%2F%2Fshop.oreilly.com%2Fproduct%2F0636920034360.do%3Fcmp%3Daf-code-books-video-product_cj_0636920034360_%25zp&amp;cjsku=0636920034360"
buy_safari_link: "https://www.safaribooksonline.com/library/view/hello-startup/9781491910016/"
buy_oreilly_text: "Buy &quot;Hello, Startup: A Programmer's Guide to Building Products, Technologies, and Teams&quot; from the O'Reilly Store."
buy_safari_text: "Buy &quot;Hello, Startup: A Programmer's Guide to Building Products, Technologies, and Teams&quot; from Safari Books Online."
mobile_app_name: "Hello, Startup App"
ios_link: "#"
android_link: "#"
ios_text: "Buy &quot;Hello, Startup: A Programmer's Guide to Building Products, Technologies, and Teams&quot; from the Apple App Store."
android_text: "Buy &quot;Hello, Startup: A Programmer's Guide to Building Products, Technologies, and Teams&quot; from the Google Play Store."

resources:
  ideas: "How to come up with startup ideas; how to be more creative; a list of links to ready-made ideas you can use."
  validate: "Quick and cheap ways to do some market research to find out if you have a big idea or a complete bust."
  templates: "Free and paid templates you can use for your web and mobile apps instead of coming up with a design from scratch."
  images: "Free and paid images you can use in your startup."
  mvp: "How to define a minimal viable product; how to build prototypes quickly and cheaply."
  monetization: "Startup business models; resources such as ads, payments, subscriptions, lead gen, etc."
  distribution: "Help users find your startup through marketing, viral marketing, advertising, email, SEO, PR, and sales."
  data: "Data you can leverage to build a startup; tools for working with large amounts of data."
  languages: "Should you use Ruby, Python, Java, or PHP at your startup? Compare programming languages across many dimensions."
  frameworks: "Should you use a Ruby on Rails or Django? SpringMVC or Play? Compare server-side frameworks across many dimensions."
  databases: "Should you use SQL or NoSQL? MySQL or MongoDB? Compare database software across many dimensions."
  code: "Learn how to write code that's easy to understand, test, and modify."
  review: "How and why to setup a code review process at your startup."
  hosting: "Compare racking your own servers versus using services such as Amazon EC2, Heroku, Rackspace, and Digital Ocean."
  deploy: "Instead of deploying code manually, learn about tools such as Chef, Puppet, Ansible, and Docker."
  monitor: "Learn how to keep track all of your server metrics, business metrics, and alerts."
  jobs: "Where to look for jobs and where to find candidates."
  interview: "Interview questions you should be ready for."
  salary: "How to figure out if you're being paid a fair salary."
  equity: "How much is your equity worth? Use these tools to figure it out."
  collaboration: "Tools that help your team work together productively, such as GitHub, Slack, Google Docs, and DropBox."
  reading: "Other books, articles, and talks you should check out to learn about startups."
  community: "Find other people interested in startups around you."
  other: "Other lists of startup resources similar to this one."
# Build settings
markdown: kramdown
